controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster





    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    drive_controller:
      type: velocity_controllers/JointGroupVelocityController

    gripper_controller:
       type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    control_word_controller:
      type: forward_command_controller/ForwardCommandController

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

velocity_controller:
  ros__parameters:
    joints:
      # - joint_1
      # - joint_2
      # - joint_3
      # - joint_4
      # - joint_5
      # - joint_6
      - drive_1
    action_monitor_rate: 1000.0

position_controller:
  ros__parameters:
    joints:
      # - joint_1
      # - joint_2
      # - joint_3
      # - joint_4
      # - joint_5
      # - joint_6
      - steer_front_left_joint
      - steer_rear_left_joint
      - steer_front_right_joint
      - steer_rear_right_joint
      # - drive_1

drive_controller:
  ros__parameters:
    joints:
      - wheel_front_left_joint
      - wheel_mid_left_joint
      - wheel_rear_left_joint
      - wheel_front_right_joint
      - wheel_mid_right_joint
      - wheel_rear_right_joint
    action_monitor_rate: 1000.0
  
effort_controller:
  ros__parameters:
    joints:
      # - joint_1
      # - joint_2
      # - joint_3
      # - joint_4
      # - joint_5
      # - joint_6
      - drive_1

trajectory_controller:
  ros__parameters:
    joints:
      # - joint_1
      # - joint_2
      # - joint_3
      # - joint_4
      # - joint_5
      # - joint_6
      - drive_1
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    start_with_holding: true
    set_last_command_interface_value_as_state_on_activation: true
    action_monitor_rate: 1000.0

control_word_controller:
  ros__parameters:
    joints:
      # - joint_6
      - drive_1
    interface_name: control_word


